version: "3.3"

services:
  server-php:
    image: php:8.2-apache
    container_name: server-php
    volumes:
      - /home/happi/portainer/php-server/app:/var/www/html
    networks:
      - portainer_default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redir.rule=Host(`redir.happi.yt`)"
      - "traefik.http.routers.redir.entrypoints=websecure"
      - "traefik.http.services.redir.loadbalancer.server.port=80"
      - "traefik.http.routers.redir.service=redir"
      - "traefik.http.routers.redir.tls.certresolver=leresolver"

networks:
  portainer_default:
    external: true

