version: "3.3"

services:
  server-php:
    image: php:8.2-apache
    container_name: server-php
    volumes:
      - /home/happi/portainer/app/:/var/www/html
    networks:
      - portainer_default
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server-php.rule=Host(`server-php.happi.yt`)"
      - "traefik.http.routers.server-php.entrypoints=websecure"
      - "traefik.http.services.server-php.loadbalancer.server.port=80"
      - "traefik.http.routers.server-php.service=server-php"
      - "traefik.http.routers.server-php.tls.certresolver=leresolver"

networks:
  portainer_default:
    external: true
