---

services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SECRET_PATH=${SECRET_PATH}
    networks:
      - frontend
    volumes:
      - /usr/share/data/pwndrop:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.s_pwndrop.service=s_pwndrop"
      - "traefik.http.routers.s_pwndrop.entrypoints=https"
      - "traefik.http.routers.s_pwndrop.tls.certresolver=letsencrypt-http"
      - "traefik.http.routers.s_pwndrop.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.services.s_pwndrop.loadbalancer.server.port=8080"

networks:
  frontend:
    name: frontend